version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  soketi:
    image: quay.io/soketi/soketi:latest
    container_name: soketi_websocket_client
    environment:
      SOKETI_DEBUG: 1
      # Only required on production
      SOKETI_SSL_CERT: ''
      SOKETI_SSL_KEY: ''
      SOKETI_SSL_PASS: ''
      SOKETI_SSL_CA: ''
      # Driver configuration
      SOKETI_APP_MANAGER_DRIVER: array
      SOKETI_DEFAULT_APP_ID: app-id
      SOKETI_DEFAULT_APP_KEY: app-key
      SOKETI_DEFAULT_APP_SECRET: app-secret
    ports:
      - "6001:6001"
    depends_on:
      - postgres